// flow-typed signature: b09bd785948e7694bce8e209871b3afa
// flow-typed version: <<STUB>>/@nikuz/images-renderer_v0.0.4/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nikuz/images-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nikuz/images-renderer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nikuz/images-renderer/dst/bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nikuz/images-renderer/dst/bundle.js' {
  declare module.exports: $Exports<'@nikuz/images-renderer/dst/bundle'>;
}
