// flow-typed signature: 6ae39c0860d1deb578033d50f518b369
// flow-typed version: <<STUB>>/@nikuz/images-core_v0.0.9/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nikuz/images-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nikuz/images-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nikuz/images-core/dst/bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nikuz/images-core/dst/bundle.js' {
  declare module.exports: $Exports<'@nikuz/images-core/dst/bundle'>;
}
